package net.peercraft.network.turn;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.zip.CRC32;

/** Strict RFC 8489 framing, RFC 8656 address encoding and SHA-1 long-term integrity. */
public final class StunCodec {
    public static final int COOKIE = 0x2112A442;
    public static final int BINDING_REQUEST = 0x0001, BINDING_SUCCESS = 0x0101;
    public static final int ALLOCATE_REQUEST = 0x0003, ALLOCATE_SUCCESS = 0x0103;
    public static final int REFRESH_REQUEST = 0x0004, REFRESH_SUCCESS = 0x0104;
    public static final int CREATE_PERMISSION_REQUEST = 0x0008, CREATE_PERMISSION_SUCCESS = 0x0108;
    public static final int CHANNEL_BIND_REQUEST = 0x0009, CHANNEL_BIND_SUCCESS = 0x0109;
    public static final int DATA_INDICATION = 0x0017;
    public static final int MAPPED_ADDRESS = 0x0001, USERNAME = 0x0006, MESSAGE_INTEGRITY = 0x0008;
    public static final int ERROR_CODE = 0x0009, CHANNEL_NUMBER = 0x000c, LIFETIME = 0x000d;
    public static final int XOR_PEER_ADDRESS = 0x0012, DATA = 0x0013, REALM = 0x0014, NONCE = 0x0015;
    public static final int XOR_RELAYED_ADDRESS = 0x0016, REQUESTED_TRANSPORT = 0x0019;
    public static final int XOR_MAPPED_ADDRESS = 0x0020, FINGERPRINT = 0x8028;
    private static final SecureRandom RANDOM = new SecureRandom();
    private StunCodec() { }

    public static byte[] newTransactionId() { byte[] id = new byte[12]; RANDOM.nextBytes(id); return id; }
    public static byte[] bindingRequest(byte[] id) throws IOException { return encode(BINDING_REQUEST, id, Collections.<Attribute>emptyList(), null); }
    public static Attribute attribute(int type, byte[] value) { return new Attribute(type, value, -1); }
    public static Attribute textAttribute(int type, String value) { return attribute(type, value.getBytes(StandardCharsets.UTF_8)); }
    public static Attribute integerAttribute(int type, int value) { return attribute(type, ByteBuffer.allocate(4).putInt(value).array()); }

    public static byte[] encode(int type, byte[] id, List<Attribute> attributes, byte[] integrityKey) throws IOException {
        if ((type & 0xc000) != 0 || id == null || id.length != 12) throw new IOException("Invalid STUN header");
        ByteArrayOutputStream body = new ByteArrayOutputStream();
        for (Attribute attribute : attributes) {
            if (attribute.type == MESSAGE_INTEGRITY || attribute.type == FINGERPRINT) throw new IOException("Integrity attributes are generated by codec");
            putAttribute(body, attribute.type, attribute.value);
        }
        int contentLength = body.size() + (integrityKey == null ? 0 : 24);
        if (contentLength > 65515) throw new IOException("STUN message exceeds datagram limit");
        ByteBuffer header = ByteBuffer.allocate(20);
        header.putShort((short) type).putShort((short) contentLength).putInt(COOKIE).put(id);
        ByteArrayOutputStream result = new ByteArrayOutputStream(); result.write(header.array()); result.write(body.toByteArray());
        if (integrityKey != null) putAttribute(result, MESSAGE_INTEGRITY, hmac(result.toByteArray(), integrityKey));
        return result.toByteArray();
    }

    public static Message parse(byte[] bytes) throws IOException {
        if (bytes == null || bytes.length < 20 || bytes.length > 65535) throw new IOException("Truncated STUN message");
        ByteBuffer in = ByteBuffer.wrap(bytes);
        int type = in.getShort() & 0xffff, length = in.getShort() & 0xffff;
        if ((type & 0xc000) != 0 || (length & 3) != 0 || length + 20 != bytes.length || in.getInt() != COOKIE)
            throw new IOException("Malformed STUN header");
        byte[] id = new byte[12]; in.get(id);
        List<Attribute> attributes = new ArrayList<Attribute>();
        boolean integritySeen = false, fingerprintSeen = false;
        while (in.hasRemaining()) {
            if (in.remaining() < 4) throw new IOException("Truncated STUN attribute");
            int offset = in.position(), attributeType = in.getShort() & 0xffff, size = in.getShort() & 0xffff;
            int padded = (size + 3) & ~3;
            if (padded > in.remaining() || fingerprintSeen) throw new IOException("Malformed STUN attribute");
            if (integritySeen && attributeType != FINGERPRINT) throw new IOException("Attribute follows STUN integrity");
            if (attributeType == MESSAGE_INTEGRITY) { if (integritySeen || size != 20) throw new IOException("Invalid integrity attribute"); integritySeen = true; }
            if (attributeType == FINGERPRINT) { if (size != 4) throw new IOException("Invalid STUN fingerprint"); fingerprintSeen = true; }
            byte[] value = new byte[size]; in.get(value); in.position(offset + 4 + padded);
            attributes.add(new Attribute(attributeType, value, offset));
        }
        Message result = new Message(type, id, attributes, bytes.clone());
        Attribute fingerprint = result.attribute(FINGERPRINT);
        if (fingerprint != null) {
            CRC32 crc = new CRC32(); crc.update(bytes, 0, fingerprint.offset);
            if (((int) crc.getValue() ^ 0x5354554e) != ByteBuffer.wrap(fingerprint.value).getInt()) throw new IOException("STUN fingerprint mismatch");
        }
        return result;
    }

    public static byte[] longTermKey(String username, String realm, String password) throws IOException {
        try { return MessageDigest.getInstance("MD5").digest((username + ":" + realm + ":" + password).getBytes(StandardCharsets.UTF_8)); }
        catch (GeneralSecurityException ex) { throw new IOException("Long-term authentication unavailable", ex); }
    }
    public static boolean verifyIntegrity(Message message, byte[] key) throws IOException {
        Attribute integrity = message.attribute(MESSAGE_INTEGRITY);
        if (integrity == null || key == null) return false;
        byte[] input = Arrays.copyOf(message.raw, integrity.offset);
        ByteBuffer.wrap(input).putShort(2, (short) (integrity.offset + 24 - 20));
        return MessageDigest.isEqual(integrity.value, hmac(input, key));
    }

    public static Attribute xorAddressAttribute(int type, InetSocketAddress address, byte[] transactionId) throws IOException {
        if (address == null || address.isUnresolved() || transactionId == null || transactionId.length != 12) throw new IOException("Invalid TURN address");
        byte[] ip = address.getAddress().getAddress();
        if (ip.length != 4 && ip.length != 16) throw new IOException("Unsupported address family");
        ByteBuffer out = ByteBuffer.allocate(4 + ip.length);
        out.put((byte) 0).put((byte) (ip.length == 4 ? 1 : 2)).putShort((short) (address.getPort() ^ (COOKIE >>> 16)));
        byte[] mask = ByteBuffer.allocate(16).putInt(COOKIE).put(transactionId).array();
        for (int i = 0; i < ip.length; i++) out.put((byte) (ip[i] ^ mask[i]));
        return attribute(type, out.array());
    }
    public static InetSocketAddress xorAddress(Message message, int type) throws IOException { return address(message, type, true); }
    public static InetSocketAddress mappedAddress(Message message) throws IOException {
        return message.attribute(XOR_MAPPED_ADDRESS) != null ? xorAddress(message, XOR_MAPPED_ADDRESS) : address(message, MAPPED_ADDRESS, false);
    }
    private static InetSocketAddress address(Message message, int type, boolean xor) throws IOException {
        Attribute attribute = message.attribute(type);
        if (attribute == null || attribute.value.length < 4) throw new IOException("Missing STUN address");
        ByteBuffer in = ByteBuffer.wrap(attribute.value);
        if (in.get() != 0) throw new IOException("Invalid STUN address reserved field");
        int family = in.get() & 255, port = in.getShort() & 65535;
        int size = family == 1 ? 4 : family == 2 ? 16 : -1;
        if (size < 0 || in.remaining() != size) throw new IOException("Invalid STUN address family or size");
        byte[] ip = new byte[size]; in.get(ip);
        if (xor) {
            port ^= COOKIE >>> 16;
            byte[] mask = ByteBuffer.allocate(16).putInt(COOKIE).put(message.transactionId).array();
            for (int i = 0; i < ip.length; i++) ip[i] ^= mask[i];
        }
        if (port == 0) throw new IOException("Invalid STUN address port");
        return new InetSocketAddress(InetAddress.getByAddress(ip), port);
    }
    private static byte[] hmac(byte[] bytes, byte[] key) throws IOException {
        try { Mac mac = Mac.getInstance("HmacSHA1"); mac.init(new SecretKeySpec(key, "HmacSHA1")); return mac.doFinal(bytes); }
        catch (GeneralSecurityException ex) { throw new IOException("STUN integrity unavailable", ex); }
    }
    private static void putAttribute(ByteArrayOutputStream out, int type, byte[] bytes) throws IOException {
        if (bytes.length > 65535) throw new IOException("Attribute too large");
        out.write((type >>> 8) & 255); out.write(type & 255); out.write((bytes.length >>> 8) & 255); out.write(bytes.length & 255);
        out.write(bytes);
        for (int i = bytes.length; (i & 3) != 0; i++) out.write(0);
    }

    public static final class Attribute {
        public final int type;
        public final byte[] value;
        final int offset;
        private Attribute(int type, byte[] value, int offset) { this.type = type; this.value = value.clone(); this.offset = offset; }
        public String text() { return new String(value, StandardCharsets.UTF_8); }
        public int integer() throws IOException { if (value.length != 4) throw new IOException("Invalid integer attribute"); return ByteBuffer.wrap(value).getInt(); }
    }
    public static final class Message {
        public final int type;
        public final byte[] transactionId;
        public final List<Attribute> attributes;
        private final byte[] raw;
        private Message(int type, byte[] id, List<Attribute> attrs, byte[] raw) {
            this.type = type; this.transactionId = id; this.attributes = Collections.unmodifiableList(attrs); this.raw = raw;
        }
        public boolean matches(byte[] id) { return MessageDigest.isEqual(transactionId, id); }
        public Attribute attribute(int type) {
            for (Attribute attribute : attributes) if (attribute.type == type) return attribute;
            return null;
        }
        public int errorCode() throws IOException {
            Attribute attribute = attribute(ERROR_CODE);
            if (attribute == null || attribute.value.length < 4) throw new IOException("Missing TURN error code");
            int hundred = attribute.value[2] & 7, remainder = attribute.value[3] & 255;
            if (hundred < 3 || hundred > 6 || remainder > 99) throw new IOException("Invalid TURN error code");
            return hundred * 100 + remainder;
        }
    }
}
